function RTW_rtwnameSIDMap() {
	this.rtwnameHashMap = new Array();
	this.sidHashMap = new Array();
	this.rtwnameHashMap["<Root>"] = {sid: "pid_reg"};
	this.sidHashMap["pid_reg"] = {rtwname: "<Root>"};
	this.rtwnameHashMap["<S1>"] = {sid: "pid_reg:5"};
	this.sidHashMap["pid_reg:5"] = {rtwname: "<S1>"};
	this.rtwnameHashMap["<Root>/Constant"] = {sid: "pid_reg:19"};
	this.sidHashMap["pid_reg:19"] = {rtwname: "<Root>/Constant"};
	this.rtwnameHashMap["<Root>/Gain"] = {sid: "pid_reg:13"};
	this.sidHashMap["pid_reg:13"] = {rtwname: "<Root>/Gain"};
	this.rtwnameHashMap["<Root>/Gain1"] = {sid: "pid_reg:15"};
	this.sidHashMap["pid_reg:15"] = {rtwname: "<Root>/Gain1"};
	this.rtwnameHashMap["<Root>/Integrator"] = {sid: "pid_reg:21"};
	this.sidHashMap["pid_reg:21"] = {rtwname: "<Root>/Integrator"};
	this.rtwnameHashMap["<Root>/PID Controller"] = {sid: "pid_reg:5"};
	this.sidHashMap["pid_reg:5"] = {rtwname: "<Root>/PID Controller"};
	this.rtwnameHashMap["<Root>/Scope"] = {sid: "pid_reg:3"};
	this.sidHashMap["pid_reg:3"] = {rtwname: "<Root>/Scope"};
	this.rtwnameHashMap["<Root>/Sum1"] = {sid: "pid_reg:20"};
	this.sidHashMap["pid_reg:20"] = {rtwname: "<Root>/Sum1"};
	this.rtwnameHashMap["<S1>/u"] = {sid: "pid_reg:5:1"};
	this.sidHashMap["pid_reg:5:1"] = {rtwname: "<S1>/u"};
	this.rtwnameHashMap["<S1>/Derivative Gain"] = {sid: "pid_reg:5:1699"};
	this.sidHashMap["pid_reg:5:1699"] = {rtwname: "<S1>/Derivative Gain"};
	this.rtwnameHashMap["<S1>/Filter"] = {sid: "pid_reg:5:1701"};
	this.sidHashMap["pid_reg:5:1701"] = {rtwname: "<S1>/Filter"};
	this.rtwnameHashMap["<S1>/Filter Coefficient"] = {sid: "pid_reg:5:1702"};
	this.sidHashMap["pid_reg:5:1702"] = {rtwname: "<S1>/Filter Coefficient"};
	this.rtwnameHashMap["<S1>/Integral Gain"] = {sid: "pid_reg:5:1698"};
	this.sidHashMap["pid_reg:5:1698"] = {rtwname: "<S1>/Integral Gain"};
	this.rtwnameHashMap["<S1>/Integrator"] = {sid: "pid_reg:5:1700"};
	this.sidHashMap["pid_reg:5:1700"] = {rtwname: "<S1>/Integrator"};
	this.rtwnameHashMap["<S1>/Proportional Gain"] = {sid: "pid_reg:5:1697"};
	this.sidHashMap["pid_reg:5:1697"] = {rtwname: "<S1>/Proportional Gain"};
	this.rtwnameHashMap["<S1>/Saturate"] = {sid: "pid_reg:5:1704"};
	this.sidHashMap["pid_reg:5:1704"] = {rtwname: "<S1>/Saturate"};
	this.rtwnameHashMap["<S1>/Sum"] = {sid: "pid_reg:5:1696"};
	this.sidHashMap["pid_reg:5:1696"] = {rtwname: "<S1>/Sum"};
	this.rtwnameHashMap["<S1>/SumD"] = {sid: "pid_reg:5:1703"};
	this.sidHashMap["pid_reg:5:1703"] = {rtwname: "<S1>/SumD"};
	this.rtwnameHashMap["<S1>/y"] = {sid: "pid_reg:5:10"};
	this.sidHashMap["pid_reg:5:10"] = {rtwname: "<S1>/y"};
	this.getSID = function(rtwname) { return this.rtwnameHashMap[rtwname];}
	this.getRtwname = function(sid) { return this.sidHashMap[sid];}
}
RTW_rtwnameSIDMap.instance = new RTW_rtwnameSIDMap();
